# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Therapy Nottingham"
  url = "#hero"
  weight = 10

[[main]]
  name = "About"
  identifier = "AboutMenu"
  weight = 20

[[main]]
  parent = "AboutMenu"
  name = "About therapy"
  url = "#about_therapy"
  weight = 3
  
[[main]]
  parent = "AboutMenu"
  name = "How I work"
  url = "/how_I_work/"
  weight = 5
  
[[main]]
  parent = "AboutMenu"
  name = "COVID-19"
  url = "/covid-19/"
  weight = 7

[[main]]
  name = "Resources"
  identifier = "ResourcesMenu"
  weight = 250
  
[[main]]
  parent = "ResourcesMenu"
  name = "What to do in a mental health crisis"
  url = "/what_to_do_in_a_mental_health_crisis/"
  weight = 1

[[main]]
  name = "Fees"
  url = "fees/"
  weight = 30

[[main]]
  name = "Privacy"
  url = "privacy/"
  weight = 70

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
